version: '3.8'
services:
  # real-estate-backend:
  #   container_name: real-estate-backend
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #   build:
  #     context: ./

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

    # caddy:
    #   image: caddy/caddy:2.2.1-alpine
    #   container_name: caddy-service
    #   restart: unless-stopped
    #   ports:
    #     - '80:80'
    #     - '443:443'
    #   volumes:
    #     - $PWD/Caddyfile:/etc/caddy/Caddyfile
    #     - $PWD/site:/srv
    #     - caddy_data:/data
    #     - caddy_config:/config
# volumes:
#   caddy_data:
#   caddy_config:
volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
